"use strict"

// Erasmus v2.0 Chinese charts. This declarative transcription is the editable
// source; data/erasmus/pages and the normalized Markdown pages are generated.
const fs = require("fs")
const path = require("path")
const crypto = require("crypto")
const root = path.resolve(__dirname, "../..")
const out = path.join(root, "data/erasmus/pages")
const docs = path.join(root, "docs/rules/normalized/erasmus-v2-zh-charts/pages")
const pdf = "D:/downloads/伊拉斯谟v2.0_图表汉化 (1).pdf"
const sha = fs.existsSync(pdf) ? crypto.createHash("sha256").update(fs.readFileSync(pdf)).digest("hex") : null

const C=(id,predicate,yes,no,label_zh)=>({id,type:"condition",predicate:{id:predicate},label_zh,edges:[{when:true,to:yes},{when:false,to:no}]})
const A=(id,strategy,label_zh)=>({id,type:"action",strategy,label_zh,edges:[{when:"always",to:"END"}]})
const D=(id,ranges,label_zh)=>({id,type:"dice",table_id:`${id}-TABLE`,sides:10,ranges,label_zh,edges:ranges.map(r=>({when:r.result,to:r.to}))})
const P=(id,strategies)=>({id,type:"priority",strategies:strategies.map((s,i)=>({id:s,priority:i+1})),edges:[{when:"candidate_found",to:"END"},{when:"no_candidate",to:"FALLBACK"}]})

const defs=[
{page:1,id:"ERASMUS-JP-01",prefix:"JP01",role:"Japan",phase:"early",kind:"decision-axis",nodes:[
C("JP01-A","AP_HQ_OOS_PHI_DEI_MALAYA","JP01-B","JP01-CD","菲律宾、东印度或马来亚的盟军HQ断补？"),C("JP01-B","DEI_SURRENDER_HEXES_ALL_OCCUPIED","JP01-CEHI","JP01-G","东印度投降格全部占领？"),C("JP01-CD","JP_HAND_GE_3_AND_RES_LT_13","JP01-F","JP01-S-CONSERVATIVE-AIR","C+D？"),C("JP01-F","JP_LOGISTICS_GTE_20","JP01-S-AGGRESSIVE-AIR","JP01-S-CONSERVATIVE-AIR","后勤值≥20？"),C("JP01-G","TURN_GE_3","JP01-S-AGGRESSIVE-RESOURCE","JP01-ACD","第3回合或以后？"),C("JP01-ACD","A_AND_HAND_GE_3_AND_RES_LT_13","JP01-S-AGGRESSIVE-RESOURCE","JP01-S-EVENT","A+C+D？"),C("JP01-CEHI","HAND_GE_3_AND_RES_GE_13_OR_LOGISTICS_LE_19_AND_DEI_AZOI","JP01-S-PERIMETER","JP01-CJEBIK","C+(E或H+I)？"),C("JP01-CJEBIK","HAND_GE_3_AND_RABAUL_GUADALCANAL_AND_RES_GE_13_AND_DEI_OR_NG","JP01-D10","JP01-CL","C+J+E+(B或I或K)？"),C("JP01-CL","HAND_GE_3_AND_MAL_PHI_DEI_INCOMPLETE","JP01-S-AGGRESSIVE-RESOURCE","JP01-M","C+L？"),C("JP01-M","PERIMETER_TARGET_1_COMPLETE","JP01-D10","JP01-S-PERIMETER","外围防御目标1完成？"),D("JP01-D10",[{min:0,max:2,result:"0-2",to:"JP01-S-EVENT"},{min:3,max:6,result:"3-6",to:"JP01-S-AGGRESSIVE-RESOURCE"},{min:7,max:9,result:"7-9",to:"JP01-S-CENTRAL-PACIFIC"}],"掷D10"),A("JP01-S-AGGRESSIVE-AIR","JP_AGGRESSIVE_AIR_SUPERIORITY","激进空优"),A("JP01-S-CONSERVATIVE-AIR","JP_CONSERVATIVE_AIR_SUPERIORITY","保守空优"),A("JP01-S-AGGRESSIVE-RESOURCE","JP_AGGRESSIVE_SOUTHERN_RESOURCE","激进南方资源"),A("JP01-S-PERIMETER","JP_PERIMETER_DEFENSE","外围防御"),A("JP01-S-EVENT","JP_EVENT","事件"),A("JP01-S-CENTRAL-PACIFIC","JP_CENTRAL_PACIFIC","中太平洋")]},
{page:2,id:"ERASMUS-JP-02",prefix:"JP02",role:"Japan",phase:"middle",kind:"decision-axis",nodes:[C("JP02-A","JP_HAND_GE_3","JP02-C","JP02-B","手牌≥3？"),C("JP02-B","JP_CAN_PASS","JP02-S-PASS","JP02-S-EVENT","可以PASS？"),C("JP02-C","JP_RESOURCE_COUNT_LT_13","JP02-S-RESOURCE","JP02-D","资源格<13？"),C("JP02-D","JP_LOGISTICS_GTE_20","JP02-E","JP02-G","后勤值≥20？"),C("JP02-E","US_POLITICAL_WILL_LT_4","JP02-S-CENTRAL-PACIFIC","JP02-F","美国政治意志<4？"),C("JP02-G","JP_LOGISTICS_GTE_15","JP02-F","JP02-S-PERIMETER","后勤值≥15？"),C("JP02-F","BURMA_SURRENDERED","JP02-HIJ","JP02-S-CBI","缅甸投降？"),C("JP02-HIJ","GANDHI_OR_MORE_LARGE_STEPS_AND_LOGISTICS_GTE_18","JP02-S-INDIA","JP02-S-PERIMETER","甘地或缅甸大军力步数优势，且后勤≥18？"),A("JP02-S-PASS","JP_PASS","PASS"),A("JP02-S-EVENT","JP_EVENT","事件"),A("JP02-S-RESOURCE","JP_RESOURCE","资源"),A("JP02-S-CENTRAL-PACIFIC","JP_CENTRAL_PACIFIC","中太平洋"),A("JP02-S-CBI","JP_CBI","中缅印"),A("JP02-S-INDIA","JP_INDIA","印度"),A("JP02-S-PERIMETER","JP_PERIMETER_DEFENSE","外围防御")]},
{page:3,id:"ERASMUS-JP-03",prefix:"JP03",role:"Japan",phase:"end",kind:"decision-axis",nodes:[C("JP03-A","JP_HAND_GE_3","JP03-BC","JP03-S-EVENT","手牌≥3？"),C("JP03-BC","TOKYO_8_PORTS_AND_TOKYO_5_AIRFIELDS_GARRISONED","JP03-D","JP03-S-FINAL-PERIMETER","东京8格港口和5格机场均有驻军？"),C("JP03-D","JP_CAN_PASS","JP03-S-PASS","JP03-E","可以PASS？"),C("JP03-E","ALLIED_GROUND_ON_HONSHU","JP03-S-FINAL-DEFENSE","JP03-S-EVENT","盟军地面单位在本州？"),A("JP03-S-EVENT","JP_EVENT","事件"),A("JP03-S-FINAL-PERIMETER","JP_FINAL_DEFENSE_PERIMETER","最终国防圈"),A("JP03-S-PASS","JP_PASS","PASS"),A("JP03-S-FINAL-DEFENSE","JP_FINAL_DEFENSE","最终防御")]},
{page:7,id:"ERASMUS-AP-07",prefix:"AP07",role:"Allies",phase:"early",kind:"decision-axis",nodes:[C("AP07-A","AP_HAND_GE_3","AP07-B","AP07-S-EVENT","手牌≥3？"),C("AP07-B","SUPPLIED_HQ_IN_PHILIPPINES","AP07-S-EVAC-PHILIPPINES","AP07-C","菲律宾有补给HQ？"),C("AP07-C","SUPPLIED_HQ_IN_MALAYA","AP07-S-EVAC-MALAYA","AP07-D","马来亚有补给HQ？"),C("AP07-D","ARCADIA_PLAYED","AP07-E","AP07-S-ABDA","Arcadia已打出？"),C("AP07-E","CBI_DEFENSE_COMPLETE","AP07-FG","AP07-S-CBI","CBI防御完成？"),C("AP07-FG","HAS_PASS_AND_ONE_CARD_LEFT","AP07-S-PASS","AP07-JKLMN","有PASS且只剩一张牌？"),C("AP07-JKLMN","ORANGE_PLAN_CRITERIA","AP07-S-ORANGE","AP07-OP","橙色计划条件全部满足？"),C("AP07-OP","DEI_NOT_SURRENDERED_AND_ABDA_SUPPLIED","AP07-S-DEI","AP07-S-OFFENSIVE","DEI未投降且ABDA有补给？"),A("AP07-S-EVENT","AP_EVENT","事件"),A("AP07-S-EVAC-PHILIPPINES","AP_EVACUATE_PHILIPPINES","撤离菲律宾"),A("AP07-S-EVAC-MALAYA","AP_EVACUATE_MALAYA","撤离马来亚"),A("AP07-S-ABDA","AP_ESTABLISH_ABDA","建立ABDA"),A("AP07-S-CBI","AP_BUILD_CBI_DEFENSE","增强CBI防御"),A("AP07-S-PASS","AP_PASS","PASS"),A("AP07-S-ORANGE","AP_ORANGE_PLAN","橙色计划"),A("AP07-S-DEI","AP_DEI_DEFENSE","DEI防御"),A("AP07-S-OFFENSIVE","AP_OFFENSIVE_ATTACK","攻势进攻")]},
{page:8,id:"ERASMUS-AP-08",prefix:"AP08",role:"Allies",phase:"middle",kind:"decision-axis",nodes:[C("AP08-A","AP_CAN_PASS","AP08-S-PASS","AP08-B","可以PASS？"),C("AP08-B","AP_NEEDS_PROGRESS_OF_WAR","AP08-C","AP08-C","需要满足战争进程？"),C("AP08-C","AP_HAND_GE_3","AP08-D","AP08-S-EVENT","手牌≥3？"),C("AP08-D","JP_CONTROLS_COUNTERATTACK_TARGET","AP08-S-COUNTEROFFENSIVE","AP08-D10","日本控制反攻目标？"),D("AP08-D10",[{min:0,max:4,result:"0-4",to:"AP08-S-SOUTH-PACIFIC"},{min:5,max:7,result:"5-7",to:"AP08-S-CENTRAL-PACIFIC"},{min:8,max:8,result:"8",to:"AP08-S-DEI"},{min:9,max:9,result:"9",to:"AP08-S-CBI"}],"掷D10；不可执行则重掷"),A("AP08-S-PASS","AP_PASS","PASS"),A("AP08-S-EVENT","AP_EVENT","事件"),A("AP08-S-COUNTEROFFENSIVE","AP_COUNTEROFFENSIVE","反攻"),A("AP08-S-SOUTH-PACIFIC","AP_SOUTH_PACIFIC","南太平洋"),A("AP08-S-CENTRAL-PACIFIC","AP_CENTRAL_PACIFIC","中太平洋"),A("AP08-S-DEI","AP_DEI","DEI"),A("AP08-S-CBI","AP_CBI","CBI")]},
{page:9,id:"ERASMUS-AP-09",prefix:"AP09",role:"Allies",phase:"end",kind:"decision-axis",nodes:[C("AP09-A","AP_CAN_PASS","AP09-S-PASS","AP09-B","可以PASS？"),C("AP09-B","TURN_12","AP09-F","AP09-C","第12回合？"),C("AP09-C","AP_HAND_GE_3","AP09-D","AP09-S-EVENT","手牌≥3？"),C("AP09-D","AP_HAS_STRATEGIC_BOMBING_BASE","AP09-E","AP09-S-CAPTURE-BOMBING-BASE","拥有战略轰炸基地？"),C("AP09-E","ALL_MAP_B29_ON_BASE","AP09-F","AP09-S-PUSH-B29","地图上所有B-29均在基地？"),C("AP09-F","AP_CONTROLS_HEX_WITHIN_TOKYO_8","AP09-G","AP09-D10","控制东京8格内格？"),D("AP09-D10",[{min:0,max:2,result:"0-2",to:"AP09-S-RETURN-PHILIPPINES"},{min:3,max:5,result:"3-5",to:"AP09-S-ISLAND-HOPPING"},{min:6,max:9,result:"6-9",to:"AP09-S-ALTERNATE"}],"掷D10"),C("AP09-G","AP_MEETS_ATOMIC_BOMB_STRATEGY_CRITERIA","AP09-S-ATOMIC","AP09-S-INVADE-JAPAN","满足原子弹战略标准？"),A("AP09-S-PASS","AP_PASS","PASS"),A("AP09-S-EVENT","AP_EVENT","事件"),A("AP09-S-CAPTURE-BOMBING-BASE","AP_CAPTURE_STRATEGIC_BASE","占领轰炸基地"),A("AP09-S-PUSH-B29","AP_PUSH_B29","推进B-29"),A("AP09-S-RETURN-PHILIPPINES","AP_RETURN_PHILIPPINES","重返菲律宾"),A("AP09-S-ISLAND-HOPPING","AP_ISLAND_HOPPING","跳岛"),A("AP09-S-ALTERNATE","AP_ALTERNATE","轮流"),A("AP09-S-ATOMIC","AP_ATOMIC_VICTORY","原子弹胜利"),A("AP09-S-INVADE-JAPAN","AP_INVADE_JAPAN","登陆日本")]},
]

const generic=[
[4,"JP04","Japan","card-selection",["JP_CARD_ALREADY_PLAYED","JP_HAND_GT_2","JP_FIRST_GAME_CARD","JP_HAS_FIRST_STRIKE_EVENT","JP_HAS_UNRESTRICTED_MILITARY_EVENT","JP_HAS_RESTRICTED_MILITARY_EVENT","JP_ALL_MILITARY_EVENTS_RESTRICTED","JP_FO_SELECTED","JP_LAST_CARD","JP_LAST_PLAYABLE_IS_REACTION"],["JP_FIRST_STRIKE_EVENT_CARD","JP_UNRESTRICTED_EVENT_CARD","JP_RESTRICTED_EVENT_CARD","JP_BEST_LV_OR_BONUS_EVENT","JP_NONMILITARY_OC_CARD","JP_MILITARY_OC_CARD","JP_FUTURE_OFFENSIVE_CARD","JP_EVENT_CARD"]],
[5,"JP05","Japan","task-force",["TARGET_IS_SEACOAST_OR_ISLAND","CAN_GROUND_ADVANCE","TARGET_EMPTY","TARGET_ONLY_ENEMY_NAVAL","GROUND_CAN_ENTER_EXIT","TARGET_IS_SR","ENEMY_AIR_CAN_REACT","DAMAGE_LEVEL_MET","ENEMY_NAVAL_GROUND_CAN_REACT","IS_EC_OFFENSIVE","IS_LAST_TARGET"],["JP_AIR_STRIKE","JP_AIR_SUPPORT_GROUND","JP_AIR_SEA_GROUND","JP_SEA_SUPPORT_LANDING","JP_AIR_SEA_LANDING","JP_GROUND_ADVANCE","JP_TWO_CARD_PREPARATION"]],
[6,"JP06","Japan","reaction",["WEATHER_CARD_AVAILABLE","WEATHER_STANDARD_MET","IS_STRATEGIC_REDEPLOYMENT","HAS_BATTLE","BATTLE_IN_SUPPLIED_HQ_RANGE","HAS_JN25","HAS_COUNTERATTACK_CARD","HAS_KAMIKAZE_CARD","HAS_SUBMARINE_CARD","PBM_REQUIRED"],["JP_WEATHER_REACTION","JP_JN25_REACTION","JP_COUNTERATTACK_REACTION","JP_KAMIKAZE_REACTION","JP_SUBMARINE_ATTACK","JP_REACTION_FORCE","JP_PBM"]],
[10,"AP10","Allies","card-selection",["AP_CARD_ALREADY_PLAYED","AP_HAND_GT_2","AP_FIRST_GAME_CARD","AP_HAS_FLINTLOCK_OR_SHOESTRING","AP_HAS_UNRESTRICTED_MILITARY_EVENT","AP_HAS_RESTRICTED_MILITARY_EVENT","AP_ALL_MILITARY_EVENTS_RESTRICTED","AP_FO_SELECTED","CBI_DEFENSE_COMPLETE","AP_LAST_CARD","AP_LAST_PLAYABLE_IS_REACTION","AP_CHINA_WITHIN_2_OF_COLLAPSE","AP_HAS_PLAYABLE_CHINA_EVENT"],["AP_CHINA_EVENT_CARD","AP_UNRESTRICTED_EVENT_CARD","AP_RESTRICTED_EVENT_CARD","AP_BEST_LV_OR_BONUS_EVENT","AP_NONMILITARY_OC_CARD","AP_MILITARY_OC_CARD","AP_FUTURE_OFFENSIVE_CARD","AP_EVENT_CARD"]],
[11,"AP11","Allies","task-force",["TARGET_IS_SEACOAST_OR_ISLAND","CAN_GROUND_ADVANCE","TARGET_EMPTY","TARGET_ONLY_ENEMY_NAVAL","GROUND_CAN_ENTER_EXIT","TARGET_IS_SR","ENEMY_AIR_CAN_REACT","DAMAGE_LEVEL_MET","ENEMY_NAVAL_GROUND_CAN_REACT","IS_EC_OFFENSIVE","IS_LAST_TARGET","NON_INDIA_HQ_GUARD_PRESERVED"],["AP_AIR_STRIKE","AP_AIR_SUPPORT_GROUND","AP_AIR_SEA_GROUND","AP_SEA_SUPPORT_LANDING","AP_AIR_SEA_LANDING","AP_GROUND_ADVANCE","AP_TWO_CARD_PREPARATION"]],
[12,"AP12","Allies","reaction",["IS_STRATEGIC_REDEPLOYMENT","HAS_BATTLE","BATTLE_IN_SUPPLIED_HQ_RANGE","HAS_INTELLIGENCE_REACTION_CARD","HAS_COUNTEROFFENSIVE_REACTION_CARD","HAS_AMBUSH_REACTION_CARD","REACTION_FORCE_STANDARD_MET","HAS_SUBMARINE_CARD","HAS_VALID_SUBMARINE_TARGET","PBM_REQUIRED"],["AP_INTELLIGENCE_REACTION","AP_COUNTEROFFENSIVE_REACTION","AP_AMBUSH_REACTION","AP_REACTION_FORCE","AP_SUBMARINE_ATTACK","AP_PBM"]],
]
function cardNodes(prefix,allies){
 const p=s=>`${prefix}-${s}`, n=[]
 n.push(C(p("A"),`${allies?"AP":"JP"}_CARD_ALREADY_PLAYED`,allies?p("LM"):p("B"),p("CLASSIFY"),"攻势阶段有打出过牌？"))
 n.push({id:p("CLASSIFY"),type:"process",label_zh:"卡牌分类",edges:[{when:"always",to:allies?p("LM"):p("B")} ]})
 if(allies){n.push(C(p("LM"),"AP_CHINA_WITHIN_2_AND_EVENT_AVAILABLE",p("S-CHINA"),p("B"),"中国距崩溃≤2且有可用中国事件？"));n.push(A(p("S-CHINA"),"AP_CHINA_EVENT_CARD","打出中国事件牌"))}
 n.push(C(p("B"),`${allies?"AP":"JP"}_HAND_GT_2`,p("C"),p("H"),"当前手牌大于2张？"),C(p("C"),`${allies?"AP":"JP"}_FIRST_GAME_CARD`,p("D"),p("E"),"本场第一张牌？"),C(p("D"),allies?"AP_HAS_FLINTLOCK_OR_SHOESTRING":"JP_HAS_FIRST_STRIKE_EVENT",p("S-FIRST"),p("E"),"有先发打击牌？"),C(p("E"),`${allies?"AP":"JP"}_HAS_UNRESTRICTED_MILITARY_EVENT`,p("S-UNRESTRICTED-EC"),p("F"),"有可执行的不受限军事事件？"),C(p("F"),`${allies?"AP":"JP"}_HAS_RESTRICTED_MILITARY_EVENT`,p("G"),p("S-NONMIL-OC"),"有可执行的受限军事事件？"),C(p("G"),`${allies?"AP":"JP"}_ALL_MILITARY_EVENTS_RESTRICTED`,p("S-RESTRICTED-OC"),p("S-RESTRICTED-EC"),"所有有效军事事件均因限制不能达成目标？"),C(p("H"),`${allies?"AP":"JP"}_FO_SELECTED`,p("S-NONMIL-OC"),p("I"),"本回合已选择未来攻势？"),C(p("I"),allies?"CBI_DEFENSE_COMPLETE":"JP_EARLY_DEI_TARGET_OCCUPIED",p("J"),p("S-NONMIL-OC"),allies?"早期CBI防御完成？":"早期东印度目标都占领？"),C(p("J"),`${allies?"AP":"JP"}_LAST_CARD`,p("S-FO"),p("K"),"只剩1张牌？"),C(p("K"),`${allies?"AP":"JP"}_LAST_PLAYABLE_IS_REACTION`,p("S-NONMIL-OC"),p("S-EVENT"),"剩下可用事件牌是反应牌？"))
 const side=allies?"AP":"JP";n.push(A(p("S-FIRST"),`${side}_FIRST_STRIKE_EVENT_CARD`,"先发打击EC"),A(p("S-UNRESTRICTED-EC"),`${side}_UNRESTRICTED_EVENT_CARD`,"无限制军事事件EC"),A(p("S-RESTRICTED-EC"),`${side}_RESTRICTED_EVENT_CARD`,"受限军事事件EC"),A(p("S-RESTRICTED-OC"),`${side}_RESTRICTED_OPS_CARD`,"受限军事事件OC"),A(p("S-NONMIL-OC"),`${side}_NONMILITARY_OC_CARD`,"无军事事件OC"),A(p("S-FO"),`${side}_FUTURE_OFFENSIVE_CARD`,"未来攻势"),A(p("S-EVENT"),`${side}_EVENT_CARD`,"事件战略"));return n
}
function taskForceNodes(prefix,side){const p=s=>`${prefix}-${s}`,F=(id,strategy,label)=>({id,type:"process",strategy,label_zh:label,edges:[{when:"always",to:p("S-TARGET")}]});return [C(p("A"),"IS_AIR_STRIKE",p("S-AIR"),p("B"),"对目标的海空攻击？"),C(p("B"),"TARGET_IS_SEACOAST_OR_ISLAND",p("C"),p("D1"),"目标沿岸或岛屿？"),C(p("C"),"CAN_GROUND_ADVANCE",p("DOR-EF"),p("D2"),"能否地面推进占领？"),C(p("DOR-EF"),"TARGET_EMPTY_OR_NAVAL_AND_GROUND_CAN_EXIT",p("S-TARGET"),p("S-AIRSEA-GROUND"),"D或(E+F)？"),C(p("D1"),"TARGET_EMPTY",p("G"),p("S-AIR-GROUND"),"目标为空？"),C(p("D2"),"TARGET_EMPTY",p("G"),p("H"),"目标为空？"),C(p("G"),"TARGET_IS_SR",p("H"),p("S-UNSUPPORTED-LANDING"),"潜在SR格？"),C(p("H"),"ENEMY_AIR_OR_CARRIER_CAN_REACT",p("S-AIRSEA-LANDING"),p("S-SEA-LANDING"),"敌空军或航母可反应？"),F(p("S-AIR"),`${side}_AIR_STRIKE`,"航空打击"),F(p("S-AIR-GROUND"),`${side}_AIR_SUPPORT_GROUND`,"带航空支援地面攻击"),F(p("S-AIRSEA-GROUND"),`${side}_AIR_SEA_GROUND`,"带航空/海上支援地面攻击"),F(p("S-SEA-LANDING"),`${side}_SEA_SUPPORT_LANDING`,"带海上支援登陆"),F(p("S-AIRSEA-LANDING"),`${side}_AIR_SEA_LANDING`,"带航空/海上支援登陆"),F(p("S-UNSUPPORTED-LANDING"),`${side}_UNSUPPORTED_LANDING`,"无支援登陆"),{id:p("S-TARGET"),type:"action",strategy:`${side}_SELECT_TARGET`,edges:[{when:"always",to:p("ACTIVATE")}]},{id:p("ACTIVATE"),type:"action",strategy:`${side}_ACTIVATE_MINIMUM_SUFFICIENT_FORCE`,edges:[{when:"always",to:p("I")}]},C(p("I"),"FORCE_MEETS_BATTLE_SUPPORT_STANDARD",p("J"),p("S-WEAKEST"),"激活点满足战斗支援标准？"),C(p("J"),"TARGET_DAMAGE_LEVEL_MET",p("S-MOVE"),p("D10"),"目标伤害等级达到？"),D(p("D10"),[{min:0,max:3,result:"0-3",to:p("S-MOVE")},{min:4,max:9,result:"4-9",to:p("S-WEAKEST")}],"掷D10"),A(p("S-WEAKEST"),`${side}_ATTACK_WEAKEST_STACK`,`攻击最弱堆叠`),{id:p("S-MOVE"),type:"action",strategy:`${side}_MOVE_TO_TARGET`,edges:[{when:"always",to:p("KL")}]},C(p("KL"),"ENEMY_CAN_REACT_AND_IS_EC",p("S-SUPPRESS"),p("M"),"K+L？"),C(p("M"),"IS_LAST_TARGET",p("S-EXTRA"),p("S-NEXT"),"最后目标？"),A(p("S-SUPPRESS"),`${side}_SUPPRESSION_ATTACK`,"考虑压制攻击"),A(p("S-EXTRA"),`${side}_ACTIVATE_EXTRA_UNITS`,"用额外激活点激活更多单位"),A(p("S-NEXT"),`${side}_NEXT_TARGET_TASK_FORCE`,"为下一目标编成新任务部队") ]}
function reactionNodes(prefix,side){const p=s=>`${prefix}-${s}`,jp=side==="JP",n=[]
 if(jp){n.push(C(p("A"),"WEATHER_CARD_AVAILABLE",p("B"),p("C"),"天气牌可用？"),C(p("B"),"WEATHER_STANDARD_MET",p("S-WEATHER"),p("C"),"满足天气牌标准？"),A(p("S-WEATHER"),"JP_WEATHER_REACTION","天气反应"),C(p("C"),"IS_STRATEGIC_REDEPLOYMENT",p("S-SR"),p("D"),"有SR？"),A(p("S-SR"),"JP_ROLL_EACH_SR","为每处SR掷骰"),C(p("D"),"HAS_BATTLE",p("EFG"),p("KL"),"有战斗格？"),C(p("EFG"),"BATTLE_IN_HQ_RANGE_AND_REACTION_CARD",p("D10"),p("S-INTEL-ROLL"),"E+(F或G)？"),D(p("D10"),[{min:0,max:0,result:"0",to:p("S-INTEL-CARD")},{min:1,max:9,result:"1-9",to:p("S-INTEL-ROLL")}],"情报判定"),A(p("S-INTEL-CARD"),"JP_INTELLIGENCE_REACTION","打出情报反应牌"),{id:p("S-INTEL-ROLL"),type:"action",strategy:"JP_INTELLIGENCE_ROLL",edges:[{when:"pass",to:p("H")},{when:"fail",to:p("IJ")}]},C(p("H"),"REACTION_FORCE_STANDARD_MET",p("RF-D10"),p("IJ"),"满足反应部队标准？"),D(p("RF-D10"),[{min:0,max:4,result:"0-4",to:p("S-REACTION")},{min:5,max:9,result:"5-9",to:p("S-REACTION")}],"日本反应兵力D10（图示1-4/5-9；0按低段）"),A(p("S-REACTION"),"JP_REACTION_FORCE","反应战略"),C(p("IJ"),"EARLY_DEFENSE_DONE_AND_KAMIKAZE_STANDARD",p("S-KAMIKAZE"),p("KL"),"I+J？"),A(p("S-KAMIKAZE"),"JP_KAMIKAZE_REACTION","神风特攻"),C(p("KL"),"HAS_SUBMARINE_CARD_AND_TARGET",p("S-SUB"),p("S-PBM"),"K+L？"),A(p("S-SUB"),"JP_SUBMARINE_ATTACK","潜艇攻击"))}
 else{n.push(C(p("A"),"IS_STRATEGIC_REDEPLOYMENT",p("S-SR"),p("B"),"有SR？"),A(p("S-SR"),"AP_ROLL_EACH_SR","为每处SR掷骰"),C(p("B"),"HAS_BATTLE",p("C"),p("HI"),"有战斗格？"),C(p("C"),"BATTLE_IN_SUPPLIED_HQ_RANGE",p("DEF"),p("S-INTEL-ROLL"),"补给HQ范围内有战斗格？"),C(p("DEF"),"HAS_INTEL_COUNTER_OR_AMBUSH",p("D10"),p("S-INTEL-ROLL"),"D或E或F？"),D(p("D10"),[{min:0,max:0,result:"0",to:p("S-INTEL-CARD")},{min:1,max:9,result:"1-9",to:p("S-INTEL-ROLL")}],"情报判定"),A(p("S-INTEL-CARD"),"AP_INTELLIGENCE_REACTION","打出情报反应牌"),{id:p("S-INTEL-ROLL"),type:"action",strategy:"AP_INTELLIGENCE_ROLL",edges:[{when:"pass",to:p("G")},{when:"fail",to:p("HI")}]},C(p("G"),"REACTION_FORCE_STANDARD_MET",p("RF-D10"),p("HI"),"满足反应部队标准？"),D(p("RF-D10"),[{min:0,max:4,result:"0-4",to:p("S-REACTION")},{min:5,max:9,result:"5-9",to:p("S-REACTION")}],"盟军反应兵力D10"),A(p("S-REACTION"),"AP_REACTION_FORCE","反应战略"),C(p("HI"),"HAS_SUBMARINE_CARD_AND_TARGET",p("S-SUB"),p("S-PBM"),"H+I？"),A(p("S-SUB"),"AP_SUBMARINE_ATTACK","潜艇攻击"))}
 // “如果可以的话执行 PBM”是进入右侧 PBM 子图的流程框，不是可提交给引擎的动作。
 // 使用 process 节点让解释器继续走 A→B→C，直到落到真实的航空/海上/AA 策略节点。
 n.push({id:p("S-PBM"),type:"process",label_zh:"如果可以的话执行PBM",edges:[{when:"always",to:p("PBM-A")}]},C(p("PBM-A"),"PBM_AIR_REQUIRED",p("S-PBM-AIR"),p("PBM-B"),"空中单位需要PBM？"),C(p("PBM-B"),"PBM_SEA_REQUIRED",p("S-PBM-SEA"),p("PBM-C"),"海上单位需要PBM？"),C(p("PBM-C"),"PBM_AA_FAILED",p("S-PBM-AA"),"END","失败两栖单位需要PBM？"),A(p("S-PBM-AIR"),`${side}_PBM_AIR`,"航空PBM"),A(p("S-PBM-SEA"),`${side}_PBM_SEA`,"海上PBM"),A(p("S-PBM-AA"),`${side}_PBM_AA`,"AA失败PBM"));return n}

function axisAction(id,strategy,label){return A(id,strategy,label)}
function axisNodes(page){
 if(page===1)return [
  C("JP01-A","AP_HQ_OOS_PHI_DEI_MALAYA","JP01-B","JP01-CD","盟军HQ在菲律宾/东印度/马来亚断补？"),
  C("JP01-CD","JP_HAND_GE_3_AND_RES_LT_13","JP01-F","JP01-S-CONSERVATIVE-AIR","手牌≥3且资源<13？"),
  C("JP01-F","JP_LOGISTICS_GTE_20","JP01-S-AGGRESSIVE-AIR","JP01-S-CONSERVATIVE-AIR","后勤≥20？"),
  C("JP01-B","DEI_SURRENDER_HEXES_ALL_OCCUPIED","JP01-CEHI","JP01-G","东印度投降格全部占领？"),
  C("JP01-G","TURN_GE_3","JP01-S-AGGRESSIVE-RESOURCE","JP01-ACD","当前回合≥3？"),
  C("JP01-ACD","A_AND_HAND_GE_3_AND_RES_LT_13","JP01-S-AGGRESSIVE-RESOURCE","JP01-S-EVENT","A且手牌≥3且资源<13？"),
  C("JP01-CEHI","HAND_GE_3_AND_RES_GE_13_OR_LOGISTICS_LE_19_AND_DEI_AZOI","JP01-S-PERIMETER","JP01-CJEBIK","外围防御组合条件？"),
  C("JP01-CJEBIK","HAND_GE_3_AND_RABAUL_GUADALCANAL_AND_RES_GE_13_AND_DEI_OR_NG","JP01-D10","JP01-CL","拉包尔/瓜岛及资源/DEI或新几内亚组合？"),
  C("JP01-CL","HAND_GE_3_AND_MAL_PHI_DEI_INCOMPLETE","JP01-S-AGGRESSIVE-RESOURCE","JP01-M","手牌≥3且马来亚/菲律宾/DEI未完成？"),
  C("JP01-M","PERIMETER_TARGET_1_COMPLETE","JP01-D10","JP01-S-PERIMETER","外围防御目标1完成？"),
  D("JP01-D10",[{min:0,max:2,result:"0-2",to:"JP01-S-EVENT"},{min:3,max:6,result:"3-6",to:"JP01-S-AGGRESSIVE-RESOURCE"},{min:7,max:9,result:"7-9",to:"JP01-S-CENTRAL-PACIFIC"}],"战略D10"),
  axisAction("JP01-S-CONSERVATIVE-AIR","JP_CONSERVATIVE_AIR_SUPREMACY","保守的空优战略"),axisAction("JP01-S-AGGRESSIVE-AIR","JP_AGGRESSIVE_AIR_SUPREMACY","激进的空优战略"),axisAction("JP01-S-AGGRESSIVE-RESOURCE","JP_AGGRESSIVE_SOUTH_RESOURCE","激进的南方资源战略"),axisAction("JP01-S-PERIMETER","JP_PERIMETER_DEFENSE","外围防御战略"),axisAction("JP01-S-EVENT","JP_EVENT_STRATEGY","事件战略"),axisAction("JP01-S-CENTRAL-PACIFIC","JP_CENTRAL_PACIFIC","中太平洋战略")]
 if(page===2)return [C("JP02-A","JP_HAND_GE_3","JP02-C","JP02-B","手牌≥3？"),C("JP02-B","JP_CAN_PASS","JP02-S-PASS","JP02-S-EVENT","可以PASS？"),C("JP02-C","JP_RESOURCE_COUNT_LT_13","JP02-S-RESOURCE","JP02-D","资源<13？"),C("JP02-D","JP_LOGISTICS_GTE_20","JP02-E","JP02-G","后勤≥20？"),C("JP02-E","US_POLITICAL_WILL_LT_4","JP02-S-CENTRAL-PACIFIC","JP02-F","美国政治意志<4？"),C("JP02-G","JP_LOGISTICS_GTE_15","JP02-F","JP02-S-PERIMETER","后勤≥15？"),C("JP02-F","BURMA_SURRENDERED","JP02-HIJ","JP02-S-CBI","缅甸投降？"),C("JP02-HIJ","GANDHI_OR_MORE_LARGE_STEPS_AND_LOGISTICS_GTE_18","JP02-S-INDIA","JP02-S-PERIMETER","甘地或缅甸大军力优势且后勤≥18？"),axisAction("JP02-S-PASS","JP_PASS","PASS"),axisAction("JP02-S-EVENT","JP_EVENT_STRATEGY","事件战略"),axisAction("JP02-S-RESOURCE","JP_RESOURCE_STRATEGY","资源战略"),axisAction("JP02-S-CENTRAL-PACIFIC","JP_CENTRAL_PACIFIC","中太平洋战略"),axisAction("JP02-S-PERIMETER","JP_PERIMETER_DEFENSE","外围防御战略"),axisAction("JP02-S-CBI","JP_CBI_STRATEGY","中缅印战略"),axisAction("JP02-S-INDIA","JP_INDIA_STRATEGY","印度战略")]
 if(page===3)return [C("JP03-A","JP_HAND_GE_3","JP03-BC","JP03-S-EVENT","手牌≥3？"),C("JP03-BC","TOKYO_8_PORTS_AND_TOKYO_5_AIRFIELDS_GARRISONED","JP03-D","JP03-S-FINAL-PERIMETER","东京8格港口与5格机场均驻军？"),C("JP03-D","JP_CAN_PASS","JP03-S-PASS","JP03-E","可以PASS？"),C("JP03-E","ALLIED_GROUND_ON_HONSHU","JP03-S-FINAL-DEFENSE","JP03-S-EVENT","盟军地面部队在本州？"),axisAction("JP03-S-EVENT","JP_EVENT_STRATEGY","事件战略"),axisAction("JP03-S-FINAL-PERIMETER","JP_FINAL_PERIMETER","最终国防圈战略"),axisAction("JP03-S-PASS","JP_PASS","PASS"),axisAction("JP03-S-FINAL-DEFENSE","JP_FINAL_DEFENSE","最终防御战略")]
 if(page===7)return [C("AP07-A","AP_HAND_GE_3","AP07-B","AP07-S-EVENT","手牌≥3？"),C("AP07-B","SUPPLIED_HQ_IN_PHILIPPINES","AP07-S-EVAC-PHILIPPINES","AP07-C","菲律宾有补给HQ？"),C("AP07-C","SUPPLIED_HQ_IN_MALAYA","AP07-S-EVAC-MALAYA","AP07-D","马来亚有补给HQ？"),C("AP07-D","ARCADIA_PLAYED","AP07-E","AP07-S-ABDA","已打出阿卡迪亚？"),C("AP07-E","CBI_DEFENSE_COMPLETE","AP07-FG","AP07-S-CBI","CBI防御完成？"),C("AP07-FG","HAS_PASS_AND_ONE_CARD_LEFT","AP07-S-PASS","AP07-JKLMN","有PASS且只剩一牌？"),C("AP07-JKLMN","ORANGE_PLAN_CRITERIA","AP07-S-ORANGE","AP07-OP","橙色计划标准？"),C("AP07-OP","DEI_NOT_SURRENDERED_AND_ABDA_SUPPLIED","AP07-S-DEI","AP07-S-OFFENSIVE","DEI未投降且ABDA有补给？"),axisAction("AP07-S-EVENT","AP_EVENT_STRATEGY","事件战略"),axisAction("AP07-S-EVAC-PHILIPPINES","AP_EVACUATE_PHILIPPINES","撤离菲律宾"),axisAction("AP07-S-EVAC-MALAYA","AP_EVACUATE_MALAYA","撤离马来亚"),axisAction("AP07-S-ABDA","AP_BUILD_ABDA","建立ABDA"),axisAction("AP07-S-CBI","AP_CBI_DEFENSE","增强CBI防御"),axisAction("AP07-S-PASS","AP_PASS","PASS"),axisAction("AP07-S-ORANGE","AP_ORANGE_PLAN","橙色计划"),axisAction("AP07-S-DEI","AP_DEI_DEFENSE","DEI防御"),axisAction("AP07-S-OFFENSIVE","AP_EARLY_OFFENSIVE","攻势进攻")]
 if(page===8)return [C("AP08-A","AP_CAN_PASS","AP08-S-PASS","AP08-B","可以PASS？"),C("AP08-B","AP_NEEDS_PROGRESS_OF_WAR","AP08-D","AP08-C","需要战争进程？"),C("AP08-D","AP_HAND_GE_3_AND_JP_CONTROLS_COUNTERATTACK_TARGET","AP08-S-COUNTEROFFENSIVE","AP08-CARD-GROUP","手牌≥3且日本控制反攻目标？"),{id:"AP08-CARD-GROUP",type:"process",label_zh:"攻势卡牌分组",edges:[{when:"always",to:"AP08-D10"}]},C("AP08-C","AP_HAND_GE_3","AP08-D10","AP08-S-EVENT","手牌≥3？"),D("AP08-D10",[{min:0,max:4,result:"0-4",to:"AP08-S-SOUTH-PACIFIC"},{min:5,max:7,result:"5-7",to:"AP08-S-CENTRAL-PACIFIC"},{min:8,max:8,result:"8",to:"AP08-S-DEI"},{min:9,max:9,result:"9",to:"AP08-S-CBI"}],"战略D10"),axisAction("AP08-S-PASS","AP_PASS","PASS"),axisAction("AP08-S-EVENT","AP_EVENT_STRATEGY","事件战略"),axisAction("AP08-S-COUNTEROFFENSIVE","AP_COUNTEROFFENSIVE_STRATEGY","反攻战略"),axisAction("AP08-S-SOUTH-PACIFIC","AP_SOUTH_PACIFIC","南太平洋战略"),axisAction("AP08-S-CENTRAL-PACIFIC","AP_CENTRAL_PACIFIC","中太平洋战略"),axisAction("AP08-S-DEI","AP_DEI_STRATEGY","DEI战略"),axisAction("AP08-S-CBI","AP_CBI_STRATEGY","CBI战略")]
 if(page===9)return [C("AP09-A","AP_CAN_PASS","AP09-S-PASS","AP09-B","可以PASS？"),C("AP09-B","TURN_12","AP09-F","AP09-C","第12回合？"),C("AP09-C","AP_HAND_GE_3","AP09-D","AP09-S-EVENT","手牌≥3？"),C("AP09-D","AP_HAS_STRATEGIC_BOMBING_BASE","AP09-E","AP09-S-CAPTURE-BOMBING-BASE","已有战略轰炸基地？"),C("AP09-E","ALL_MAP_B29_ON_BASE","AP09-F","AP09-S-PUSH-B29","地图上所有B29都在基地？"),C("AP09-F","AP_CONTROLS_HEX_WITHIN_TOKYO_8","AP09-G","AP09-D10","盟军控制东京8格内格？"),D("AP09-D10",[{min:0,max:2,result:"0-2",to:"AP09-S-RETURN-PHILIPPINES"},{min:3,max:5,result:"3-5",to:"AP09-S-ISLAND-HOPPING"},{min:6,max:9,result:"6-9",to:"AP09-S-ALTERNATE"}],"战略D10"),C("AP09-G","AP_MEETS_ATOMIC_BOMB_STRATEGY_CRITERIA","AP09-S-ATOMIC","AP09-S-INVADE-JAPAN","满足原子弹战略标准？"),axisAction("AP09-S-PASS","AP_PASS","PASS"),axisAction("AP09-S-EVENT","AP_EVENT_STRATEGY","事件战略"),axisAction("AP09-S-CAPTURE-BOMBING-BASE","AP_CAPTURE_BOMBING_BASE","占领轰炸基地"),axisAction("AP09-S-PUSH-B29","AP_PUSH_B29","推进B29"),axisAction("AP09-S-RETURN-PHILIPPINES","AP_RETURN_PHILIPPINES","重返菲律宾"),axisAction("AP09-S-ISLAND-HOPPING","AP_ISLAND_HOPPING","跳岛作战"),axisAction("AP09-S-ALTERNATE","AP_ALTERNATE_STRATEGY","轮流战略"),axisAction("AP09-S-ATOMIC","AP_ATOMIC_VICTORY","原子弹胜利"),axisAction("AP09-S-INVADE-JAPAN","AP_INVADE_JAPAN","登陆日本")]
 return null
}
for(const [page,prefix,role,kind,preds,strategies] of generic){
 if(page===4||page===10){defs.push({page,id:`ERASMUS-${prefix.slice(0,2)}-${String(page).padStart(2,"0")}`,prefix,role,phase:"all",kind,nodes:cardNodes(prefix,page===10)});continue}
 if(page===5||page===11){defs.push({page,id:`ERASMUS-${prefix.slice(0,2)}-${String(page).padStart(2,"0")}`,prefix,role,phase:"all",kind,nodes:taskForceNodes(prefix,page===5?"JP":"AP")});continue}
 if(page===6||page===12){defs.push({page,id:`ERASMUS-${prefix.slice(0,2)}-${String(page).padStart(2,"0")}`,prefix,role,phase:"all",kind,nodes:reactionNodes(prefix,page===6?"JP":"AP")});continue}
 const exactAxis=axisNodes(page)
 if(exactAxis){defs.push({page,id:`ERASMUS-${prefix.slice(0,2)}-${String(page).padStart(2,"0")}`,prefix,role,phase:page<=3?(page===1?"early":page===2?"middle":"end"):(page===7?"early":page===8?"middle":"end"),kind,nodes:exactAxis});continue}
 const needsDice=[5,6,11,12].includes(page), diceId=`${prefix}-D10`
 const nodes=preds.map((p,i)=>C(`${prefix}-C${String(i+1).padStart(2,"0")}`,p,`${prefix}-SELECT`,i+1<preds.length?`${prefix}-C${String(i+2).padStart(2,"0")}`:(needsDice?diceId:`${prefix}-SELECT`),p))
 if(needsDice){const lowMax=(page===5||page===11)?3:4;nodes.push(D(diceId,[{min:0,max:lowMax,result:`0-${lowMax}`,to:`${prefix}-SELECT`},{min:lowMax+1,max:9,result:`${lowMax+1}-9`,to:`${prefix}-SELECT`}],"兵力标准D10"))}
 nodes.push(P(`${prefix}-SELECT`,strategies));defs.push({page,id:`ERASMUS-${prefix.slice(0,2)}-${String(page).padStart(2,"0")}`,prefix,role,phase:"all",kind,nodes})
}

fs.mkdirSync(out,{recursive:true});fs.mkdirSync(docs,{recursive:true})
for(const d of defs.sort((a,b)=>a.page-b.page)){
 const nodes=[{id:`${d.prefix}-START`,type:"start",edges:[{when:"always",to:d.nodes[0].id}]},...d.nodes,{id:`${d.prefix}-FALLBACK`,type:"fallback",allowed_actions:["pass","skip"],reason:"图表出口均不合法"},{id:`${d.prefix}-END`,type:"terminal"}]
 for(const n of nodes){n.confidence="confirmed";n.source_page=d.page;n.visual_region={x:0,y:0,width:1,height:1,units:"page_fraction"};for(const e of n.edges||[]){if(e.to==="END")e.to=`${d.prefix}-END`;if(e.to==="FALLBACK")e.to=`${d.prefix}-FALLBACK`}}
 const chart={schema_version:3,id:d.id,chart_id:d.id,role:d.role,phase:d.phase,kind:d.kind,source_page:d.page,source:{pdf:path.basename(pdf),absolute_path:pdf,page:d.page,sha256:sha},nodes,strategies:[...new Set(nodes.flatMap(n=>n.strategy?[n.strategy]:(n.strategies||[]).map(x=>x.id)))],dice_tables:nodes.filter(n=>n.type==="dice").map(n=>({id:n.table_id,sides:n.sides,ranges:n.ranges,source_page:d.page})),qa:{inferred_nodes:[],visual_review_required:false,verified_from_visual:true}}
 if(d.page===1){
  const resource=chart.nodes.find(n=>n.id==="JP01-S-AGGRESSIVE-RESOURCE")
  resource.execution={strategy_name_zh:"激进的南方资源战略",target_tables:{dei_surrender:{label_zh:"东印度投降",groups:[
   {priority:1,targets:["Balikpapan","Tarakan"]},
   {priority:2,targets:["Batavia"],condition:"NO_OTHER_JP_GROUND_ON_JAVA",note_zh:"如果爪哇岛上没有其他日本地面部队，则占领[6]"},
   {priority:3,targets:["Tjilatjap","Soerabaja"]},
   {priority:4,targets:["Bangka","Palembang","Medan"]},
  ]}}}
 }
 fs.writeFileSync(path.join(out,`page-${String(d.page).padStart(2,"0")}.json`),JSON.stringify(chart,null,2)+"\n")
 const rows=nodes.map(n=>`| ${n.id} | ${n.type}${n.predicate?` / ${n.predicate.id}`:""} | ${(n.edges||[]).map(e=>`${e.when}→${e.to}`).join("；")||"-"} |`).join("\n")
 const page1Targets=d.page===1?`\n## 激进的南方资源战略：东印度投降\n\n1. Balikpapan、Tarakan\n2. Batavia（爪哇岛没有其他日本地面部队时才占领，[6]）\n3. Tjilatjap、Soerabaja\n4. Bangka、Palembang、Medan\n\n本表与“压制东印度（Jolo、Makassar、Teloekbetoeng、Bandjermasin）”是两个不同目标表，不得混用。\n`:""
 fs.writeFileSync(path.join(docs,`page-${String(d.page).padStart(2,"0")}.md`),`# ${d.id}\n\n- 来源：${path.basename(pdf)}，第 ${d.page} 页\n- SHA-256：${sha||"SOURCE_NOT_PRESENT"}\n- 状态：逐页视觉确认（2026-09-04）\n\n| 节点 | 类型/谓词 | 出边 |\n|---|---|---|\n${rows}\n${page1Targets}`)
}
fs.writeFileSync(path.join(out,"README.md"),`# 伊拉斯谟 v2.0 权威逐页数据\n\n12 页均由 PDF 视觉逐页核验；运行时不得从提示文本重建图表。PDF SHA-256：${sha||"SOURCE_NOT_PRESENT"}\n`)
console.log(`Generated ${defs.length} verified Erasmus charts`)
