"use strict"
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm')
function fixture(){let refined=true;const coords=[2909,3009,3209,3709,3813,3814,3416,4017,4415,4715,3305,3306,2813,2915],owned=new Set(coords),board=coords.map(id=>({id,name:String(id),port:true,airfield:true,region:'Pacific'}));const c={map:board,hex_to_int:x=>x,LAST_BOARD_HEX:9999,SHORT_CAMPAIGN_SCENARIO:5,EVEN_SHORT_CAMPAIGN_SCENARIO:8,em_cfg:()=>({japan_campaign_refinement:refined}),querySpaceControlled:(h,f)=>f===0?owned.has(h):!owned.has(h),get_distance:(a,b)=>Math.abs(a-b),get_map_data:h=>board.find(x=>x.id===h)};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../js/server/bots/erasmus_campaign_v2.js','utf8').split('// BEGIN CAMPAIGN V2\n')[1].split('// END CAMPAIGN V2')[0],c);return {c,owned,board,setRefined:x=>refined=x}}
test('expanded Japanese geography and guards exclude enemy control and preserve old six-place policy',()=>{const {c,owned,board,setRefined}=fixture(),v={sid:8,turn:5},units=[{id:27,faction:0,class:'ground',location:2813,cf:4},{id:32,faction:0,class:'ground',location:3305,cf:12}];let ds=c.ej_island_defense(v,c.ec_map(),units);assert.equal(ds.length,14);assert.equal(ds.find(x=>x.hex===2813).reserveId,27);assert.equal(ds.find(x=>x.hex===3305).reserveId,32);owned.delete(3416);assert(!c.ej_island_defense(v,c.ec_map(),units).some(x=>x.hex===3416));setRefined(false);assert.equal(c.ej_island_defense(v,c.ec_map(),units).length,6)})
test('unfinished opening Philippines can advance, completed keys and later turns keep garrisons',()=>{const {c,owned}=fixture(),v={sid:5,turn:3};owned.delete(2915);assert.equal(c.ej_guard_required(v,2813),false);owned.add(2915);assert.equal(c.ej_guard_required(v,2813),true);owned.delete(2915);v.turn=5;assert.equal(c.ej_guard_required(v,2813),true);v.sid=8;v.turn=4;assert.equal(c.ej_guard_required(v,2813),true)})
test('legal PBM stay strictly outranks filling another island; surplus and forced departure remain selectable',()=>{const {c}=fixture(),u={id:27,class:'ground',faction:0,service:'army'},position={version:1,role:'Japan',turn:5,bases:[{hex:2813,port:true},{hex:3416,port:true}],units:[{...u,location:2813}],islandDefense:[{hex:2813,reserveId:27,groundCount:1},{hex:3416,reserveId:null,groundCount:0,priority:480}],garrisonReserveIds:[27],focus:3416,captured:[]};const stay=c.ec_position_score(2813,0,u,2813,position).score,go=c.ec_position_score(3416,0,u,2813,position).score;assert(stay[1]<go[1]);assert(Array.isArray(go),'source illegal in forced retreat still has legal fallback');position.units.push({id:28,class:'ground',faction:0,location:2813});const surplus=c.ec_position_score(3416,0,{...u,id:28},2813,position);assert(Array.isArray(surplus.score))})
test('Japanese refinement persists only in its explicit profile, including env all and recovery',()=>{const c={process:{env:{EOTS_OPT_PROFILE:'all'}},G:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/../js/server/bots/erasmus_config.js','utf8')+';this.api={resolve:em_bot_config,load:em_load_state_config,get:em_cfg}',c);const p=c.api.resolve('erasmus-japan-campaign-v2-1','Japan');assert.equal(p.japan_campaign_refinement,1);assert.equal(p.campaign_v2,1);assert.equal(p.japan_campaign_planner,1);assert(!('allies_campaign_refinement' in p));c.G.ai_profile={Japan:p};c.api.load('Japan');assert.equal(c.api.get().japan_campaign_refinement,1);for(const id of ['erasmus-japan-campaign-v2','erasmus-campaign-v2','erasmus-campaign-v2-1','erasmus-campaign-v2-2']){const old=c.api.resolve(id,'Japan');assert(!('japan_campaign_refinement' in old));c.G.ai_profile={Japan:old};c.api.load('Japan');assert(!('japan_campaign_refinement' in c.api.get()))}})

test('real delegated chart guard covers all eight added bases, releases surplus, and allows reaction',()=>{const Module=require('node:module'),path=require('node:path'),file=path.resolve(__dirname,'../rules.js'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(file,'utf8')+String.raw`
exports.__guardProbe=state=>{G=state;L=G.L;R="Japan";_load();try{return rules_query_snapshot(()=>{G.turn=5;G.location.fill(NOT_USED);G.reduced=[];G.offensive.attacker=JP;const output=[];for(const c of [3416,4017,4415,4715,3305,3306,2813,2915]){const h=hex_to_int(c);is_space_controlled(h,JP);G.supply_cache[h]|=JP_CONTROLLED;G.location[27]=h;G.location[32]=NOT_USED;em_set_config(em_bot_config("erasmus-japan-campaign-v2-1","Japan"));const single=eop_unit_matches_target(27,"Japan",null,TOKYO);G.location[32]=h;const extra=eop_unit_matches_target(32,"Japan",null,TOKYO);G.offensive.attacker=AP;const reaction=eop_unit_matches_target(27,"Japan",null,TOKYO);G.offensive.attacker=JP;em_set_config(em_bot_config("erasmus-japan-campaign-v2","Japan"));const old=eop_unit_matches_target(27,"Japan",null,TOKYO);output.push({c,single,extra,reaction,old});G.location[27]=NOT_USED}return output},JP)}finally{em_reset_config();_save()}};
`,file);const r=m.exports,s=r.setup(20263525,'1943-1945 (The Even Shorter Campaign)',{}),before=JSON.stringify(s),checks=r.__guardProbe(s);assert.equal(checks.length,8);for(const x of checks){assert.equal(x.single,false,String(x.c));assert.equal(x.extra,true);assert.equal(x.reaction,true);assert.equal(x.old,true)}assert.equal(JSON.stringify(s),before)})
