"use strict"
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),Module=require('module'),path=require('path'),vm=require('vm'),{validateAction,stateDigest}=require('./match-run');
function load(){const f=path.resolve('rules.js'),m=new Module(f,module);m.filename=f;m.paths=Module._nodeModulePaths(path.dirname(f));const fixtures=fs.readFileSync('tests/campaign-air-offensive.test.js','utf8'),start=fixtures.indexOf('exports.__goalFixture'),end=fixtures.indexOf('\n`,FILE);');assert(start>=0&&end>start);m._compile(fs.readFileSync(f,'utf8').replace('// END CAMPAIGN V2','exports.__v2Plan=ec_plan;exports.__base1Functions={targets:ec_strategic_preparation_targets,assemble:ec_offensive_assembly_tasks,conflict:ec_preparation_conflicts,release:ec_resource_followup_ground};\n// END CAMPAIGN V2')+'\n'+fixtures.slice(start,end)+String.raw`
exports.__separatedFixture=s=>{const f=exports.__centralFixture(s);G=s;L=G.L;R=AP;_load();G.location[f.ground[0]]=hex_to_int(3821);G.location[f.ground[1]]=hex_to_int(3023);G.reduced=[32];check_supply();_save();return f};
exports.__resumeFixture=s=>{G=s;L=G.L;R="Allies";_load();reset_offensive();G.active=AP;G.active_stack=[];G.L=L={P:"offensive_segment",L:{P:"goal_fixture_return"}};_save()};
exports.__base1Plan=s=>{const v=exports.view(s,"Allies");G=s;L=G.L;R="Allies";_load();em_set_config(em_bot_config("erasmus-campaign-v2-3","Allies"));try{return exports.__v2Plan(v,{role:"Allies"})}finally{em_reset_config();_save()}};
`,f);return m.exports}
test('new flags are explicit, persisted by role and absent from all original IDs even with env all',()=>{const c={process:{env:{EOTS_OPT_PROFILE:'all'}},G:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('js/server/bots/erasmus_config.js','utf8')+';this.api={resolve:em_bot_config,load:em_load_state_config,get:em_cfg}',c);for(const id of ['erasmus-campaign','erasmus-japan-campaign','erasmus-campaign-v2','erasmus-campaign-v2-1','erasmus-campaign-v2-2','erasmus-japan-campaign-v2-1']){const p=c.api.resolve(id,id.includes('japan')?'Japan':'Allies');assert(!('allies_campaign_offensive_refinement'in p));assert(!('japan_campaign_opening_refinement'in p))}const p=c.api.resolve('erasmus-campaign-v2-3','Allies');assert.equal(p.allies_campaign_offensive_refinement,1);c.G.ai_profile={Allies:p};c.api.load('Allies');assert.equal(c.api.get().allies_campaign_offensive_refinement,1)});
test('separated real ground/fleet can form target-bound two-card central assembly and complete legal offensive replay',{timeout:60000},()=>{const r=load();let s=r.setup(20264091,'1943-1945 (The Even Shorter Campaign)',{headless_moves:true}),f=r.__separatedFixture(s),before=stateDigest(s),p=r.__base1Plan(s),t=p.tasks.find(t=>t.objective==='OFFENSIVE_ASSEMBLE');assert.equal(stateDigest(s),before);assert(t,'autonomous planner must choose a real future assault assembly '+JSON.stringify({tasks:p.tasks,blockers:p.blockers,goal:p.objective}));assert.equal(t.followUpTarget,f.target);assert(t.attackWitness.groundIds.length>=2);assert(t.attackWitness.requiredActivations>t.requiredUnits.length);assert(t.attackWitness.pCaptureEstimate>0);const original=JSON.parse(JSON.stringify(s)),actions=[],traces=[];for(let i=1;i<160&&s.L?.P!=='goal_fixture_return';i++){const role=Array.isArray(s.active)?s.active.slice().sort()[0]:s.active,v=r.view(s,role),d=r.bots[role==='Allies'?'erasmus-campaign-v2-3':'erasmus-japan-campaign-v2-2'].decide(v,{role,seed:20264091,actionOrdinal:i});validateAction(v,d);traces.push({role,action:d.action,arg:typeof d.argument!=="object"?d.argument:d.argument?.action??null,plan:d.argument?.__ai?.plan?.tasks?.map(t=>({hex:t.hex,units:t.movementUnitIds,obj:t.objective}))});actions.push([role,d.action,JSON.parse(JSON.stringify(d.argument??null))]);s=r.action(s,role,d.action,d.argument)}assert.equal(s.L.P,'goal_fixture_return');assert(t.movementUnitIds.every(id=>s.location[id]===t.hex),JSON.stringify({expected:t,positions:t.movementUnitIds.map(id=>[id,s.location[id]]),traces:traces.map(x=>({...x,arg:typeof x.arg==="object"&&x.arg?{focus:x.arg.focus,units:x.arg.units,mode:x.arg.move_type}:x.arg}))}));let replay=original;for(const[role,a,arg]of actions)replay=r.action(replay,role,a,arg??undefined);assert.equal(stateDigest(replay),stateDigest(s));
 // The constructed return label stands in for the real next-card script window.
 r.__resumeFixture(s);const secondStart=JSON.parse(JSON.stringify(s)),second=[];let assaulted=false;
 for(let i=1;i<180&&s.L?.P!=='goal_fixture_return';i++){const role=Array.isArray(s.active)?s.active.slice().sort()[0]:s.active,v=r.view(s,role),d=r.bots[role==='Allies'?'erasmus-campaign-v2-3':'erasmus-japan-campaign-v2-2'].decide(v,{role,seed:20264091,actionOrdinal:160+i});validateAction(v,d);second.push([role,d.action,JSON.parse(JSON.stringify(d.argument??null))]);s=r.action(s,role,d.action,d.argument);assaulted ||= s.offensive?.battle_hexes?.includes(f.target)}
 assert(assaulted,'prepared real ground/fleet must declare the guarded followup');assert.equal(r.query(s,'Allies',{name:'rules_query',fn:'querySpaceControlled',args:[f.target,1]}),true);
 let again=secondStart;for(const[role,a,arg]of second)again=r.action(again,role,a,arg??undefined);assert.equal(stateDigest(again),stateDigest(s))});
test('current-held quota blocks reserve release despite extra historical capture entries, and preparation conflict protects future escort',()=>{const c={em_cfg:()=>({campaign_planner:1,allies_campaign_refinement:1,allies_campaign_offensive_refinement:1}),querySpaceControlled:h=>c.held.has(h)};c.held=new Set([1,2,3,4]);vm.createContext(c);vm.runInContext(fs.readFileSync('js/server/bots/erasmus_campaign_v2.js','utf8').replace('// END CAMPAIGN V2','globalThis.a={release:ec_resource_followup_ground,conflict:ec_preparation_conflicts};\n// END CAMPAIGN V2'),c);const u={id:195,location:1},env={view:{turn:11,capture:[1,2,3,4,5],pow:4},faction:1,powGap:0,units:[],byHex:new Map([[1,{resource:true}]]),board:[],victory:{jpResources:3,atomic:{noStrategicBombingFailure:true,b29InRangeOfTokyo:true},blockade:{startedTurn:0},resourceTargets:[535]}};assert.equal(c.a.release(u,env,535),false);c.held.add(5);assert.equal(c.a.release(u,env,535),true);assert.equal(c.a.release(u,env,887),false);const prep={objective:'OFFENSIVE_ASSEMBLE',hex:1001,attackWitness:{groundIds:[195],escortIds:[134],supportIds:[]}},away={hex:833,movementUnitIds:[134]};assert(c.a.conflict(prep,away));assert(c.a.conflict(away,prep))});
