"use strict"
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm")
const {validDecisionTrace}=require("./match-run")
function fixture(){let refined=true;const ctx={em_cfg:()=>({campaign_planner:1,allies_campaign_refinement:refined}),em_flag:()=>true};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+"/../js/server/bots/erasmus_campaign_v2.js","utf8").split("// BEGIN CAMPAIGN V2\n")[1].split("// END CAMPAIGN V2")[0],ctx);return {ctx,setRefined:x=>refined=x}}
test("legal battle assignment follows selected unit task and never forces an absent target",()=>{
 const {ctx,setRefined}=fixture(),plan={tasks:[{kind:"SUPPRESS",hex:761,declaresBattle:true,requiredUnits:[138],targetClasses:["air"]},{kind:"SUPPRESS",hex:674,declaresBattle:true,requiredUnits:[140],targetClasses:["air"]}]},view={active_stack:[138],actions:{action_hex:[674,761]},ai:{state:"declare_battle_hexes",windowKind:"task-force",units:[{id:49,faction:0,class:"air",location:761},{id:50,faction:0,class:"air",location:674}]}};
 assert.equal(ctx.ec_pick_action(view,{role:"Allies"},plan).argument,761);
 view.active_stack=[140];assert.equal(ctx.ec_pick_action(view,{role:"Allies"},plan).argument,674);
 view.actions.action_hex=[761];assert.equal(ctx.ec_pick_action(view,{role:"Allies"},plan),null);
 view.active_stack=[138];view.ai.windowKind="reaction";assert.equal(ctx.ec_pick_action(view,{role:"Allies"},plan),null);
 view.ai.windowKind="task-force";setRefined(false);assert.equal(ctx.ec_pick_action(view,{role:"Allies"},plan),null)
})
test("blockade deadline uses actual next national judgement and existing start",()=>{const {ctx}=fixture();assert.equal(ctx.ec_blockade_can_finish({turn:11},{nextJudgementTurn:11,startedTurn:0}),false);assert.equal(ctx.ec_blockade_can_finish({turn:10},{nextJudgementTurn:10,startedTurn:0}),true);assert.equal(ctx.ec_blockade_can_finish({turn:11},{nextJudgementTurn:11,startedTurn:9}),true)})
test("trace validator accepts only registered campaign policy versions with required metadata",()=>{for(const policy of ["campaign-v1","campaign-v2.0","campaign-v2.1"])assert(validDecisionTrace({node:"task",chart:"CAMPAIGN",campaign:{},policy}));assert(!validDecisionTrace({node:"task",chart:"CAMPAIGN",campaign:{},policy:"campaign-v999"}));assert(!validDecisionTrace({node:"task",chart:"CAMPAIGN",policy:"campaign-v2.1"}));assert(!validDecisionTrace({chart:"CAMPAIGN",campaign:{},policy:"campaign-v2.1"}))})
test("refinement is explicit, restores from saved profile, and never leaks to old or Japanese profiles",()=>{const c={process:{env:{EOTS_OPT_PROFILE:"all"}},G:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+"/../js/server/bots/erasmus_config.js","utf8")+";this.api={resolve:em_bot_config,load:em_load_state_config,get:em_cfg}",c);const p=c.api.resolve("erasmus-campaign-v2-1","Allies");assert.equal(p.allies_campaign_refinement,1);c.G.ai_profile={Allies:p};c.api.load("Allies");assert.equal(c.api.get().allies_campaign_refinement,1);for(const id of ["erasmus-campaign","erasmus-campaign-v2","erasmus-japan-campaign-v2","erasmus-v2-opt-v5"]){const old=c.api.resolve(id,id.includes("japan")?"Japan":"Allies");assert(!("allies_campaign_refinement" in old));c.G.ai_profile={Allies:old};c.api.load("Allies");assert(!("allies_campaign_refinement" in c.api.get()))}})

test("established home invasion ground cannot be spent on a distant PoW raid, but can advance to the last key",()=>{const {ctx,setRefined}=fixture();ctx.querySpaceControlled=(h,f)=>h===761;ctx.get_distance=(a,b)=>({"761:703":2,"1088:703":15,"732:703":1}[a+":"+b]??Math.abs(a-b));const env={view:{turn:12},faction:1,homelandFoothold:true,victory:{homelandKeys:[761,703]},units:[{id:190,faction:1,class:"ground",location:761}]},task={hex:1088,movementUnitIds:[190],objective:"POW"};assert.equal(ctx.ec_preserves_home_force(task,env),false);task.hex=703;assert.equal(ctx.ec_preserves_home_force(task,env),true);task.hex=732;assert.equal(ctx.ec_preserves_home_force(task,env),true);task.hex=1088;setRefined(false);assert.equal(ctx.ec_preserves_home_force(task,env),true)})
test("T9 missed bombing deadline changes candidate home drive at card window, and not pre-bombing reinforcement",()=>{const {ctx,setRefined}=fixture();ctx.map=[];ctx.SHORT_CAMPAIGN_SCENARIO=1;ctx.EVEN_SHORT_CAMPAIGN_SCENARIO=8;const view={sid:1,turn:9,actions:{card:[1]},ai:{state:"offensive_segment",victory:{atomic:{noStrategicBombingFailure:false}},units:[]}};assert.equal(ctx.ec_homeland_drive(view),true);view.actions={unit:[1]};view.ai.state="reinforcements";assert.equal(ctx.ec_homeland_drive(view),false);view.actions={card:[1]};view.ai.state="offensive_segment";setRefined(false);assert.equal(ctx.ec_homeland_drive(view),false)})

test("explicit allied multi-port convergence overrides Tojo raid and ordinary occupied-focus spread",()=>{let refined=true;const source=fs.readFileSync(__dirname+"/../js/server/offensive.js","utf8"),start=source.indexOf("function headless_target_score("),end=source.indexOf("\nfunction ",start+20),c={AP:1,JP:0,ATTACK_STAGE:0,REACTION_STAGE:1,STRAT_MOVE:1,em_flag:()=>0,em_cfg:()=>({allies_campaign_refinement:refined,island_sweep:1,tojo_pressure:1}),headless_enemy_units_at:()=>({count:1,ground:1,naval:0}),headless_units_at:()=>({ground:1,hq:0}),get_distance:(a,b)=>Math.abs(a-b),get_map_data:()=>({region:"Japan"}),is_event_active:()=>false,events:{TOJO:1},set_has:(xs,x)=>xs.includes(x),G:{turn:8,offensive:{battle_hexes:[703]}},eop_next_focus_faction:()=>null};vm.createContext(c);vm.runInContext(source.slice(start,end),c);const plan={focus:703,kind:"CONQUEST",campaignTask:true,movementGroups:[{unitIds:[193,134]},{unitIds:[188,197,139,140]}]},piece={class:"naval",br:4};assert.equal(c.headless_target_score(531,true,1,"attack",true,piece,535,plan,[188,197,139,140]),null);assert.equal(c.headless_target_score(703,true,1,"attack",true,piece,535,plan,[188,197,139,140]).at(-1),703);refined=false;assert.equal(c.headless_target_score(531,true,1,"attack",true,piece,535,plan,[188,197,139,140])[0],0)})

test("1943 route consistently rejects atomic bonuses with two Manchurian resources and no legal Soviet event",()=>{const {ctx}=fixture();ctx.em_cfg=()=>({campaign_planner:1,allies_campaign_refinement:1,allies_route_commitment:1});ctx.EVEN_SHORT_CAMPAIGN_SCENARIO=8;ctx.SHORT_CAMPAIGN_SCENARIO=5;ctx.querySpaceControlled=(h,f)=>f===0;ctx.map=[{id:669,resource:true,region:"Manchuria"},{id:670,resource:true,region:"Manchuria"}];const v={sid:8,turn:10,ai:{ownCards:[],units:[],victory:{homelandKeys:[],atomic:{noStrategicBombingFailure:true,b29InRangeOfTokyo:true}}}};assert.equal(ctx.ec_route_allows_atomic(v),false);assert.equal(ctx.ec_homeland_drive(v),true);const env={view:v,board:ctx.ec_map(),faction:1};assert.equal(ctx.ec_terminal_resource_target(480,env),false);assert.equal(ctx.ec_resource_clock_target(480,env),false);v.ai.ownCards=[{name:"Soviet",allowed:["ops"]}];assert.equal(ctx.ec_route_allows_atomic(v),false);v.ai.ownCards[0].allowed=["event"];assert.equal(ctx.ec_route_allows_atomic(v),true);v.sid=5;assert.equal(ctx.ec_route_refined(v),false)})
test("resource assembly and departure of a witness force conflict in either selection order",()=>{const {ctx}=fixture(),prep={objective:"RESOURCE_ASSEMBLE",hex:421,attackWitness:{groundIds:[194,197,198],escortIds:[129,130],supportIds:[]}},move={hex:444,movementUnitIds:[198]};assert.equal(ctx.ec_preparation_conflicts(prep,move),true);assert.equal(ctx.ec_preparation_conflicts(move,prep),true);move.hex=421;assert.equal(ctx.ec_preparation_conflicts(prep,move),false);move.hex=444;move.movementUnitIds=[189];assert.equal(ctx.ec_preparation_conflicts(prep,move),false)})
test("2.2 route flag is saved only for explicit 1943 candidate and trace label is registered",()=>{const c={process:{env:{EOTS_OPT_PROFILE:"all"}},G:{}};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+"/../js/server/bots/erasmus_config.js","utf8")+";this.resolve=em_bot_config",c);assert.equal(c.resolve("erasmus-campaign-v2-2","Allies").allies_route_commitment,1);for(const id of ["erasmus-campaign-v2-1","erasmus-campaign-v2","erasmus-japan-campaign-v2"]){assert(!("allies_route_commitment" in c.resolve(id,"Allies")))}assert(validDecisionTrace({node:"task",chart:"CAMPAIGN",campaign:{},policy:"campaign-v2.2"}))})

test('central Pacific candidates include defended Truk and Guam, exclude distant south and old policies',()=>{const {ctx}=fixture();ctx.em_cfg=()=>({campaign_planner:1,allies_campaign_refinement:1,allies_route_commitment:1});ctx.EVEN_SHORT_CAMPAIGN_SCENARIO=8;ctx.hex_to_int=x=>x;ctx.TOKYO=4000;ctx.get_distance=(a,b)=>a===1000?b===2813?20:4:Math.abs(a-b);ctx.querySpaceControlled=(h,f)=>f===1?h===1000:h!==1000;ctx.AMPH_MOVE=8;ctx.queryAspRemaining=()=>5;ctx.queryGroupMovementDestinations=()=>({reachableHexes:[4017,3814],aspCost:1});const env={view:{sid:8,turn:7},faction:1,budget:5,hq:{id:80},cardId:1,moves:new Map(),garrisonReserve:new Set(),board:[{hex:1000,port:true},{hex:4017,port:true,region:'Caroline'},{hex:3814,port:false,airfield:true,region:'Oceania'},{hex:2813,port:true,region:'Philippines'}],available:[{id:1,class:'ground',asp:true,location:1000},{id:2,class:'naval',location:1000}],units:[{id:30,faction:0,class:'ground',location:4017}]};const hs=ctx.ec_central_pacific_targets(env);assert(hs.includes(4017));assert(hs.includes(3814));assert(!hs.includes(2813));env.view.sid=5;assert.equal(ctx.ec_central_pacific_targets(env).length,0);env.view.sid=8;env.view.turn=12;assert.equal(ctx.ec_central_pacific_targets(env).length,0)})
