"use strict"
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),Module=require('module'),path=require('path'),{stateDigest}=require('./match-run');
function load(){const file=path.resolve('rules.js'),m=new Module(file,module);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(file,'utf8')+String.raw`
exports.__koreaFixture=(s,{hq=2909,enemy=3307,carrier=true,islands=true}={})=>{G=s;L=G.L;R="Allies";_load();G.active=AP;G.location.fill(NOT_USED);G.control=null;G.non_control=[];G.turn=8;G.reduced=[];G.inter_service=[0,0];G.offensive.active_units=[[],[186,134]];G.offensive.active_cards=[1];G.offensive.naval_move_distance=15;G.offensive.air_move_distance=3;G.offensive.stage=POST_BATTLE_STAGE;for(let h=1;h<=LAST_BOARD_HEX;h++)G.supply_cache[h]&=~JP_CONTROLLED;G.location[186]=hex_to_int(3305);G.location[80]=hex_to_int(hq);if(carrier)G.location[134]=hex_to_int(3305);if(enemy){G.location[5]=TOKYO;G.location[23]=hex_to_int(enemy);G.supply_cache[TOKYO]|=JP_CONTROLLED;G.supply_cache[G.location[23]]|=JP_CONTROLLED}if(!islands)for(const h of[2909,3009,3209])G.supply_cache[hex_to_int(h)]|=JP_CONTROLLED;check_steady_supply();_save();return {ground:186,carrier:134,korea:hex_to_int(3305),rear:hex_to_int(hq),islands:[hex_to_int(2909),hex_to_int(3009),hex_to_int(3209)]}};
exports.__koreaPbm=(s,candidates)=>{const v=exports.view(s,"Allies");G=s;L=G.L;R="Allies";_load();em_set_config(em_bot_config("erasmus-campaign-v2-3","Allies"));try{return rules_query_snapshot(()=>{const position=EOTS_CAMPAIGN_V2.positioningContext(v,{role:"Allies",tasks:[],campaign:{objectiveHex:hex_to_int(2909)},garrisonReserveIds:[]}),piece={...pieces[134],id:134},legal=candidates || queryPbmDestinations(134,{}),scope=EOTS_CAMPAIGN_V2.positionProjectionScope(position,piece,G.location[134],legal),scores=legal.map(hex=>({hex,...EOTS_CAMPAIGN_V2.pbmScore(hex,AP,piece,G.location[134],{campaignPositioning:position},scope)})).filter(r=>Array.isArray(r.score));scores.sort((a,b)=>headless_score_lt(a.score,b.score)?-1:headless_score_lt(b.score,a.score)?1:a.hex-b.hex);return {legal,scores,pick:scores[0]}},AP)}finally{em_reset_config();_save()}};
exports.__koreaMoveGate=(s,id)=>{G=s;L=G.L;R="Allies";_load();em_set_config(em_bot_config(id,"Allies"));try{return rules_query_snapshot(()=>{const h=hex_to_int(3305);G.location[186]=hex_to_int(2909);G.supply_cache[h]|=JP_CONTROLLED;return headless_campaign_landing_supply(h,AP,[186])},AP)}finally{em_reset_config();_save()}};
`,file);return m.exports}
const clone=x=>JSON.parse(JSON.stringify(x));function setup(r,o){const s=r.setup(20264090,'1943-1945 (The Even Shorter Campaign)',{headless_moves:true});return {s,f:r.__koreaFixture(s,o)}}function ask(r,s,opts,role='Allies'){const before=stateDigest(s),q=r.query(s,role,{name:'rules_query',fn:'queryCampaignSupplyProjection',args:[{faction:1,protectedIds:[186],...opts}]});assert.equal(stateDigest(s),before,'full state, caches, RNG and logs restored');return q}
test('native steady supply ignores temporary activated supply and ownership alone',{timeout:30000},()=>{const r=load(),{s,f}=setup(r,{hq:4224,enemy:0,carrier:false});assert.equal(r.query(s,'Allies',{name:'rules_query',fn:'querySupplyStatus',args:[186]}),true);assert.equal(ask(r,s,{}).supplied,false);assert(f.islands.every(h=>r.query(s,'Allies',{name:'rules_query',fn:'querySpaceControlled',args:[h,1]})));assert.equal(r.__koreaMoveGate(clone(s),'erasmus-campaign-v2-3'),false);assert.equal(r.__koreaMoveGate(clone(s),'erasmus-campaign-v2-2'),true)});
test('real carrier PBM candidates preserve Korean ground; all-risk forced subset still selects legal move',()=>{const r=load(),{s,f}=setup(r,{});assert.equal(ask(r,s,{}).supplied,true);assert.deepEqual(ask(r,s,{moves:[{unit:134,hex:f.rear}]}).protectedOosIds,[186]);const before=stateDigest(s),p=r.__koreaPbm(s);assert.equal(stateDigest(s),before);assert(p.legal.includes(f.rear),'unsafe departure is genuinely legal PBM');assert(p.pick,'safe legal alternative exists');assert.equal(ask(r,s,{moves:[{unit:134,hex:p.pick.hex}]}).supplied,true);const forced=r.__koreaPbm(s,[f.rear]);assert.equal(forced.pick.hex,f.rear);assert.equal(forced.pick.reason,'korean-supply-risk-after-support-departure')});
test('conditional direct Korea supply works without Taiwan/Okinawa and never captures real game',()=>{const r=load(),{s,f}=setup(r,{hq:4017,enemy:0,carrier:false,islands:false});s.location[186]=f.rear;const q=ask(r,s,{moves:[{unit:186,hex:f.korea}],captureHex:f.korea});assert.equal(q.supplied,true);assert.equal(q.captureGrant,false);assert.equal(q.movementGrant,false);assert(f.islands.every(h=>r.query(s,'Allies',{name:'rules_query',fn:'querySpaceControlled',args:[h,0]})))});
test('supply projection authorizes only own public ground/relocations and nonempty proof',()=>{const r=load(),{s,f}=setup(r,{});for(const opts of[{protectedIds:[]},{protectedIds:[32]},{moves:[{unit:23,hex:f.rear}]},{moves:[{unit:134,hex:f.rear},{unit:134,hex:f.korea}]},{captureHex:f.rear}])assert.equal(ask(r,s,opts).eligible,false);assert.equal(ask(r,s,{},'Japan').eligible,false)});
test('supply preparation cannot depend on the future capture to supply its own plane',()=>{const vm=require('vm');let aircraftOos=true,futureCalls=0;const c={em_cfg:()=>({campaign_planner:1,allies_campaign_refinement:1,allies_campaign_offensive_refinement:1}),em_flag:()=>false,STRAT_MOVE:1,querySpaceControlled:()=>true,get_distance:()=>2,queryGroupMovementDestinations:()=>({reachableHexes:[7],paths:{7:[1,3,5,7]}}),queryCampaignAirProjection:()=>({eligible:true,ownOosIds:aircraftOos?[160]:[],connectedResources:[],pureSeaHexes:[]}),queryCampaignSupplyProjection:()=>{futureCalls++;return {eligible:true,supplied:true,ownOosIds:[]}}};vm.createContext(c);vm.runInContext(fs.readFileSync('js/server/bots/erasmus_campaign_v2.js','utf8').replace('// END CAMPAIGN V2','globalThis.prepare=ec_korean_supply_preparation;\n// END CAMPAIGN V2'),c);const env=()=>({faction:1,view:{turn:8},powGap:0,koreanSupplyNeeds:new Map([['672:186',{target:672,groundIds:[186]}]]),koreanPreparationQueries:{count:0},available:[{id:160,class:'air',br:2,location:5}],byHex:new Map([[7,{airfield:true}]]),moves:new Map(),airProjections:new Map(),hq:{id:80}});assert.equal(c.prepare(env()).length,0);assert.equal(futureCalls,0,'future success must not excuse current unsupported aircraft');aircraftOos=false;const ready=c.prepare(env());assert.equal(ready.length,1);assert.equal(ready[0].objective,'KOREAN_SUPPLY_PREP');assert.equal(ready[0].followUpTarget,672);assert.equal(futureCalls,1)});
