param(
    [Parameter(Mandatory=$true)][string]$ZipPath,
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\.."))
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.IO.Compression.FileSystem

$zip = [System.IO.Compression.ZipFile]::OpenRead($ZipPath)
$records = [System.Collections.Generic.List[object]]::new()

function Import-ZipAsset([string]$source, [string]$relativeTarget, [string]$objectId) {
    $entry = $zip.GetEntry($source)
    if (-not $entry) { throw "Missing ZIP entry: $source" }
    $target = Join-Path $Root $relativeTarget
    $parent = Split-Path -Parent $target
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
    $input = $entry.Open()
    $output = [System.IO.File]::Create($target)
    try { $input.CopyTo($output) } finally { $output.Dispose(); $input.Dispose() }
    $records.Add([ordered]@{
        object_id = $objectId
        source = $source
        target = $relativeTarget.Replace("\\", "/")
        sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $target).Hash.ToLowerInvariant()
        bytes = (Get-Item -LiteralPath $target).Length
    })
}

try {
    foreach ($name in @("cnmap_eots.75.avif", "cnmap_eots.150.avif", "cnmap_south_pacific.75.avif", "cnmap_south_pacific.150.avif")) {
        Import-ZipAsset "empire-of-the-sun/images/$name" "images/$name" "map:$name"
    }

    foreach ($side in @(@("ap", 85), @("jp", 87))) {
        $prefix = $side[0]
        $count = [int]$side[1]
        for ($index = 0; $index -lt $count; ++$index) {
            $sourceNumber = $index + 1
            foreach ($scale in @(100, 200)) {
                $sourceName = "card_{0}_{1:d2}.{2}.avif" -f $prefix, $sourceNumber, $scale
                $targetName = "card_{0}_{1:d2}.{2}.avif" -f $prefix, $index, $scale
                Import-ZipAsset "empire-of-the-sun/cards/$sourceName" "cards/zh/$targetName" "card:${prefix}:${index}:${scale}"
            }
        }
    }
} finally {
    $zip.Dispose()
}

$css = [System.Text.StringBuilder]::new()
[void]$css.AppendLine("/* Generated by tools/localization/import_assets.ps1. */")
foreach ($side in @(@("ap", 85), @("jp", 87))) {
    $prefix = $side[0]
    $count = [int]$side[1]
    for ($index = 0; $index -lt $count; ++$index) {
        $fileNumber = "{0:d2}" -f $index
        [void]$css.AppendLine(('html[lang="zh-CN"] .card_{0}_{1}{{background-image:image-set(url(cards/zh/card_{0}_{2}.100.avif) 1x,url(cards/zh/card_{0}_{2}.200.avif) 2x)}}' -f $prefix, $index, $fileNumber))
    }
}
[System.IO.File]::WriteAllText((Join-Path $Root "cards-zh.css"), $css.ToString(), [System.Text.UTF8Encoding]::new($false))

$manifest = [ordered]@{
    schema_version = 1
    source_zip = (Resolve-Path $ZipPath).Path
    source_zip_sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $ZipPath).Hash.ToLowerInvariant()
    imported_at = (Get-Date).ToUniversalTime().ToString("o")
    mapping_note = "Legacy art numbers are one-based; current engine card indices are zero-based. JP source card 88 is not imported because no current card metadata object matches it."
    assets = $records
}
$manifestPath = Join-Path $Root "docs\localization\assets-manifest.json"
New-Item -ItemType Directory -Path (Split-Path -Parent $manifestPath) -Force | Out-Null
[System.IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 5), [System.Text.UTF8Encoding]::new($false))
