param(
    [Parameter(Mandatory=$true)][string]$ZipPath,
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\.."))
)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.IO.Compression.FileSystem

$zip = [System.IO.Compression.ZipFile]::OpenRead($ZipPath)
$records = [System.Collections.Generic.List[object]]::new()

function Import-ZipAsset([string]$source, [string]$relativeTarget, [string]$objectId) {
    $entry = $zip.GetEntry($source)
    if (-not $entry) { throw "Missing ZIP entry: $source" }
    $target = Join-Path $Root $relativeTarget
    $parent = Split-Path -Parent $target
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
    $input = $entry.Open()
    $output = [System.IO.File]::Create($target)
    try { $input.CopyTo($output) } finally { $output.Dispose(); $input.Dispose() }
    $records.Add([ordered]@{
        object_id = $objectId
        source = $source
        target = $relativeTarget.Replace("\\", "/")
        sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $target).Hash.ToLowerInvariant()
        bytes = (Get-Item -LiteralPath $target).Length
    })
}

try {
    foreach ($name in @("cnmap_eots.75.avif", "cnmap_eots.150.avif", "cnmap_south_pacific.75.avif", "cnmap_south_pacific.150.avif")) {
        Import-ZipAsset "empire-of-the-sun/images/$name" "images/$name" "map:$name"
    }

    # Card backs: legacy back art is numbered 85 (AP) / 88 (JP); the current engine
    # uses index 0 for the back (class `card_ap_0`/`card_jp_0`). Import 1:1 into 00.
    foreach ($side in @(@("ap", 85), @("jp", 88))) {
        $prefix = $side[0]
        $backNumber = [int]$side[1]
        foreach ($scale in @(100, 200)) {
            $sourceName = "card_{0}_{1:d2}.{2}.avif" -f $prefix, $backNumber, $scale
            $targetName = "card_{0}_00.{1}.avif" -f $prefix, $scale
            Import-ZipAsset "empire-of-the-sun/cards/$sourceName" "cards/zh/$targetName" "card:${prefix}:0:${scale}"
        }
    }

    # Card faces: legacy art is one-based and matches the engine's card.num exactly
    # (card 1 == card_ap_01). Import 1:1 — do NOT shift the index.
    foreach ($side in @(@("ap", 84), @("jp", 86))) {
        $prefix = $side[0]
        $count = [int]$side[1]
        for ($n = 1; $n -le $count; ++$n) {
            foreach ($scale in @(100, 200)) {
                $name = "card_{0}_{1:d2}.{2}.avif" -f $prefix, $n, $scale
                Import-ZipAsset "empire-of-the-sun/cards/$name" "cards/zh/$name" "card:${prefix}:${n}:${scale}"
            }
        }
    }
} finally {
    $zip.Dispose()
}

$css = [System.Text.StringBuilder]::new()
[void]$css.AppendLine("/* Generated by tools/localization/import_assets.ps1. */")
foreach ($side in @(@("ap", 85), @("jp", 87))) {
    $prefix = $side[0]
    $count = [int]$side[1]
    for ($index = 0; $index -lt $count; ++$index) {
        $fileNumber = "{0:d2}" -f $index
        [void]$css.AppendLine(('html[lang="zh-CN"] .card_{0}_{1}{{background-image:image-set(url(cards/zh/card_{0}_{2}.100.avif) 1x,url(cards/zh/card_{0}_{2}.200.avif) 2x)}}' -f $prefix, $index, $fileNumber))
    }
}
[System.IO.File]::WriteAllText((Join-Path $Root "cards-zh.css"), $css.ToString(), [System.Text.UTF8Encoding]::new($false))

$manifest = [ordered]@{
    schema_version = 1
    source_zip = (Resolve-Path $ZipPath).Path
    source_zip_sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $ZipPath).Hash.ToLowerInvariant()
    imported_at = (Get-Date).ToUniversalTime().ToString("o")
    mapping_note = "Card face art is one-based and matches the engine's card.num exactly (card 1 == card_ap_01). Card backs are legacy-numbered 85 (AP) / 88 (JP) and are imported to target index 00."
    assets = $records
}
$manifestPath = Join-Path $Root "docs\localization\assets-manifest.json"
New-Item -ItemType Directory -Path (Split-Path -Parent $manifestPath) -Force | Out-Null
[System.IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 5), [System.Text.UTF8Encoding]::new($false))
